\input texinfo
@settitle Sample Manual 1.0

@copying
This is the description of the application Maze

Copyright @copyright{} 2023 Egor&Ruslan&Sergey (school 21, Novosibirsk).
@end copying

@titlepage
@title Description Maze
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage



@node Top
@top GNU Sample

This manual is for GNU Sample
(version @value{VERSION}, @value{UPDATED}).



@node Description Maze
@section Description Maze
## Part 1. Реализация проекта Maze

Программа Maze, позволяет генерировать и отрисовывать идеальные лабиринты и пещеры:

Генерация лабиринта:

1. Лабиринт генерируется согласно **алгоритму Эллера**

2. Сгенерированный лабиринт не имеет изолированных областей и петель

3. Пользователем вводится размерность лабиринта: количество строк и столбцов

4. Сгенерированный лабиринт сохраняется в файл в описанном формате

5. Пользователем задаются начальная и конечная точки

6. Маршрут отображается линией толщиной 2 пикселя, проходящей через середины всех ячеек лабиринта, через которые пролегает решение

Генерация пещер:

1. Пользователем выбирается файл, в котором описан пещера по описанному формату

2. Максимальный размер пещеры - 50 х 50

3. Пользователем задаются пределы "рождения" и "смерти" клетки, а также шанс на начальную инициализацию клетки

4. Пределы "рождения" и "смерти" имеют значения от 0 до 7

5. Предусмотрен пошаговый режим отрисовки результатов работы алгоритма в двух вариантах:
  - По нажатию на кнопку следующего шага отрисовывается очередная итерация работы алгоритма
  - По нажатию на кнопку автоматической работы запускается отрисовка итераций работы алгоритма с заданной частотой

@bye